import { WeaveTrace, WeaveSpan } from '../types/weave';

// Mock Weave traces matching W&B Weave schema

export const mockWeaveTraces: Record<string, WeaveTrace> = {
  'trace-memory-leak-1': {
    trace_id: 'trace-memory-leak-1',
    root_span_id: 'span-root-1',
    created_at: Date.now() - 600000,
    updated_at: Date.now() - 555000,
    spans: [
      {
        span_id: 'span-root-1',
        trace_id: 'trace-memory-leak-1',
        parent_id: null,
        name: 'detect_memory_leak',
        start_time_ms: Date.now() - 600000,
        end_time_ms: Date.now() - 555000,
        status: 'ok',
        attributes: {
          agent_id: 'agent-1',
          agent_name: 'DataPipeline-01',
          issue_type: 'memory_leak',
        },
        self_time_ms: 5000,
      },
      {
        span_id: 'span-collect-1',
        trace_id: 'trace-memory-leak-1',
        parent_id: 'span-root-1',
        name: 'collect_rss_data',
        start_time_ms: Date.now() - 600000,
        end_time_ms: Date.now() - 595000,
        status: 'ok',
        attributes: {
          rss_start_mb: 250,
          rss_end_mb: 847,
          slope_mb_per_min: 12.5,
          collection_window_seconds: 300,
        },
        self_time_ms: 5000,
      },
      {
        span_id: 'span-analyze-1',
        trace_id: 'trace-memory-leak-1',
        parent_id: 'span-root-1',
        name: 'analyze_trend',
        start_time_ms: Date.now() - 595000,
        end_time_ms: Date.now() - 575000,
        status: 'ok',
        attributes: {
          trend_type: 'linear_growth',
          confidence: 0.95,
        },
        self_time_ms: 8000,
      },
      {
        span_id: 'span-correlate-1',
        trace_id: 'trace-memory-leak-1',
        parent_id: 'span-analyze-1',
        name: 'correlate_spans',
        start_time_ms: Date.now() - 590000,
        end_time_ms: Date.now() - 575000,
        status: 'ok',
        attributes: {
          span_attribute_key: 'history_len',
          span_attribute_start: 100,
          span_attribute_end: 1200,
          correlation_coefficient: 0.98,
        },
        self_time_ms: 12000,
      },
      {
        span_id: 'span-propose-1',
        trace_id: 'trace-memory-leak-1',
        parent_id: 'span-root-1',
        name: 'propose_fix',
        start_time_ms: Date.now() - 575000,
        end_time_ms: Date.now() - 560000,
        status: 'ok',
        attributes: {
          fix_type: 'ring_buffer',
          max_size: 1000,
          eviction_strategy: 'fifo_with_summarization',
        },
        self_time_ms: 15000,
      },
      {
        span_id: 'span-generate-1',
        trace_id: 'trace-memory-leak-1',
        parent_id: 'span-propose-1',
        name: 'generate_patch',
        start_time_ms: Date.now() - 570000,
        end_time_ms: Date.now() - 560000,
        status: 'ok',
        attributes: {
          file_path: 'src/pipeline/processor.py',
          line_number: 42,
          patch_lines: 8,
        },
        self_time_ms: 10000,
      },
    ],
  },

  'trace-cpu-stall-1': {
    trace_id: 'trace-cpu-stall-1',
    root_span_id: 'span-root-2',
    created_at: Date.now() - 240000,
    updated_at: Date.now() - 215000,
    spans: [
      {
        span_id: 'span-root-2',
        trace_id: 'trace-cpu-stall-1',
        parent_id: null,
        name: 'detect_event_loop_stall',
        start_time_ms: Date.now() - 240000,
        end_time_ms: Date.now() - 215000,
        status: 'ok',
        attributes: {
          agent_id: 'agent-2',
          agent_name: 'EventProcessor-02',
          issue_type: 'event_loop_stall',
        },
        self_time_ms: 3000,
      },
      {
        span_id: 'span-measure-2',
        trace_id: 'trace-cpu-stall-1',
        parent_id: 'span-root-2',
        name: 'measure_loop_lag',
        start_time_ms: Date.now() - 240000,
        end_time_ms: Date.now() - 235000,
        status: 'ok',
        attributes: {
          loop_lag_ms: 245,
          threshold_ms: 100,
          spike_detected: true,
        },
        self_time_ms: 5000,
      },
      {
        span_id: 'span-analyze-2',
        trace_id: 'trace-cpu-stall-1',
        parent_id: 'span-root-2',
        name: 'analyze_span_self_time',
        start_time_ms: Date.now() - 235000,
        end_time_ms: Date.now() - 227000,
        status: 'ok',
        attributes: {
          blocking_operation: 'file_read',
          self_time_ms: 230,
          async_context: false,
        },
        self_time_ms: 8000,
      },
      {
        span_id: 'span-propose-2',
        trace_id: 'trace-cpu-stall-1',
        parent_id: 'span-root-2',
        name: 'propose_fix',
        start_time_ms: Date.now() - 227000,
        end_time_ms: Date.now() - 215000,
        status: 'ok',
        attributes: {
          fix_type: 'run_in_executor',
          executor_type: 'thread_pool',
        },
        self_time_ms: 12000,
      },
    ],
  },

  'trace-memory-growth-1': {
    trace_id: 'trace-memory-growth-1',
    root_span_id: 'span-root-3',
    created_at: Date.now() - 120000,
    updated_at: Date.now() - 60000,
    spans: [
      {
        span_id: 'span-root-3',
        trace_id: 'trace-memory-growth-1',
        parent_id: null,
        name: 'detect_memory_growth',
        start_time_ms: Date.now() - 120000,
        end_time_ms: Date.now() - 60000,
        status: 'ok',
        attributes: {
          agent_id: 'agent-3',
          agent_name: 'QueryEngine-03',
          issue_type: 'unbounded_cache',
        },
        self_time_ms: 5000,
      },
      {
        span_id: 'span-collect-3',
        trace_id: 'trace-memory-growth-1',
        parent_id: 'span-root-3',
        name: 'collect_rss_trajectory',
        start_time_ms: Date.now() - 120000,
        end_time_ms: Date.now() - 110000,
        status: 'ok',
        attributes: {
          rss_slope_mb_per_min: 2.1,
          measurement_window_minutes: 10,
        },
        self_time_ms: 10000,
      },
      {
        span_id: 'span-correlate-3',
        trace_id: 'trace-memory-growth-1',
        parent_id: 'span-root-3',
        name: 'correlate_with_cache',
        start_time_ms: Date.now() - 110000,
        end_time_ms: Date.now() - 90000,
        status: 'ok',
        attributes: {
          cache_size_start: 1200,
          cache_size_end: 4500,
          cache_eviction_policy: 'none',
        },
        self_time_ms: 20000,
      },
      {
        span_id: 'span-propose-3',
        trace_id: 'trace-memory-growth-1',
        parent_id: 'span-root-3',
        name: 'propose_ttl_eviction',
        start_time_ms: Date.now() - 90000,
        end_time_ms: Date.now() - 60000,
        status: 'ok',
        attributes: {
          fix_type: 'ttl_eviction',
          ttl_minutes: 30,
          redis_command: 'SETEX',
        },
        self_time_ms: 30000,
      },
    ],
  },
};

export function getWeaveTrace(traceId: string): WeaveTrace | null {
  return mockWeaveTraces[traceId] || null;
}
